---
title: An R Markdown document converted from "/Users/emmafoessing/Documents/Master/MA/Code/Master-Thesis/SDG_CART.ipynb"
output: html_document
---

# Synthetic Data Generator with a CART Model

## Libraries

```{r}
list_of_packages <- c ("synthpop", "insight", "party", "haven", "dplyr", "rpart", "rpart.plot", "randomForest", "pROC", "caret", "pracma", "here", "Hmisc", "purrr", "randomForest", "caret", "ranger")

install_if_missing <- function(p){
  if(!requireNamespace(p, quietly = TRUE)){
    install.packages(p)
  }
  library(p, character.only=TRUE)
}


lapply(list_of_packages, install_if_missing)
```

## Data

```{r}
load(file = (paste0(here(), "/cpspop.RData")))
adult <- read.csv(file = (paste0(here(),"/adult_preprocessed.csv")))
# delete NAs
adult[adult == "?"] <- NA
adult <- na.omit(adult)

adult$workclass <- as.factor(adult$workclass)
adult$education <- as.factor(adult$education)
adult$marital_status <- as.factor(adult$marital_status)
adult$relationship <- as.factor(adult$relationship)
adult$race <- as.factor(adult$race)
adult$sex <- as.factor(adult$sex)
adult$native_country <- as.factor(adult$native_country)
adult$income <- as.factor(adult$income)
adult$occupation <- as.factor(adult$occupation)
```

## Synthetic Data

```{r}
synthetic_cpspop <- syn(cpspop) #remember to set the seed
synthetic_adult <- syn(adult) #remember to set the seed
```

```{r}
# Define target variables
target_vars <- colnames(cpspop)

# Generate synthetic data for all target variables
synthetic_cpspop <- generate_synthetic_data_all(cpspop, target_vars, num_trees = 500)

# View the synthetic dataset
head(synthetic_cpspop)
```

